# Generated by Django 5.2.12 on 2026-04-18 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roaster', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeroast',
            name='resume_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
